In [14]:
A = "a"
a = 1

print A
print a

a
1


a = 3.111111111111111111111
print type(a)
a = "13.111111111111111111111"
print type(a)
a = 311111
print type(a)

a = 12
12 = a

In [24]:
a = 12
b = "hello"
print a
print b 

print "-------------------"

b = a 
print a
print b
print "-----------------------"

#b와 a같 묶여서 가진않는다
a= 98
print a
print b

12
hello
-------------------
12
12
-----------------------
98
12


In [25]:
a = "abcd"
a = a + "abcd"
print a

abcdabcd


In [44]:
a =  """Hello."What!!"  """
print a

Hello."What!!"  


In [34]:
a_list = [1,2,34,"abcd"]
print a_list

[1, 2, 34, 'abcd']


In [38]:
a_list.append("a")
print a_list

[1, 2, 34, 'abcd', 'a', 'a', 'a', 'a']


In [39]:
a_list.append("a")
print a_list

[1, 2, 34, 'abcd', 'a', 'a', 'a', 'a', 'a']


In [42]:
print a_list
a_list.insert(2,"b")
print a_list

[1, 2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']
[1, 2, 'b', 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']


In [43]:
print a_list
a_list.pop(3)
print a_list

[1, 2, 'b', 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']
[1, 2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']


In [48]:
print a_list
a_list.remove(1)
print a_list

[2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a']


ValueError: list.remove(x): x not in list

In [47]:
print a_list
a_list.remove("a")
print a_list

[2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a']
[2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a']


In [50]:
d1 = {"a":1234,"b":5678}

In [52]:
d1.keys() #리스트형태로 반환해줌

['a', 'b']

In [53]:
d1.values()

[1234, 5678]

In [54]:
d1["a"]

1234

In [59]:
a = 2
if a>0:
    print "a는 양수"
elif a == 0:
    print "a는 0"
else:
    print "a는 음수"
        

a는 양수


range(0,10)

In [60]:
range(0,10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
for i in range(0,10,2):
    print i

0
2
4
6
8


In [91]:
a = [12,34,56]
for i in a:
    print i

12
34
56


In [90]:
a = ["a","b","c","d","e","f","g","c","i"]
b = []
for i in range(0,len(a)):
    if a[i] != "c":
        b.append(a[i])
print b

['a', 'b', 'd', 'e', 'f', 'g', 'i']


In [125]:
a = [["a","b","c","d"],"f","g",["c","i"]]
b = []

                   

for i in a:
    print type(i)
    if type(i)== type([]):
        for j in i:
            print j
            if j != "c":
                b.append(j)
            else:
                pass
    else:
        if(i != "c"):
            b.append(i)
        else:
            pass
            
print b



for i in range(0,len(a)):
    for j in range(0,len(a[i])):
        print a[i]
        print a[i][j]
        print "------------"
        if a[i][j] != "c":
            b.append(a[i][j])
print b
                

<type 'list'>
a
b
c
d
<type 'str'>
<type 'str'>
<type 'list'>
c
i
['a', 'b', 'd', 'f', 'g', 'i']
['a', 'b', 'c', 'd']
a
------------
['a', 'b', 'c', 'd']
b
------------
['a', 'b', 'c', 'd']
c
------------
['a', 'b', 'c', 'd']
d
------------
f
f
------------
g
g
------------
['c', 'i']
c
------------
['c', 'i']
i
------------
['a', 'b', 'd', 'f', 'g', 'i', 'a', 'b', 'd', 'f', 'g', 'i']


In [130]:
def sum2(a,b):
    result = a + b
    return result

In [126]:
10+30

40

In [131]:
sum2(10,30)

40

In [132]:
def noinput():
    result = "Hello!!!"
    return result

In [135]:
a = noinput()
print a

Hello!!


In [136]:
def noreturn(a,b):
    temp = a + b
    print "Hello Python + :" + str(temp)

In [140]:
a = noreturn(2,3)
print a

Hello Python + :5
None


In [143]:
def noinreturn():
    print "hello!~~~~~"

In [144]:
a = noinreturn()
print a
print "-------"
noinreturn()

hello!~~~~~
None
-------
hello!~~~~~


In [146]:
def sumrandom(*args):
    result = 0
    for i in args:
        result = result + i
    return result
    

In [150]:
print sumrandom(1,2,2,3,423,4324,234234,23,32)
print sumrandom(31,321,321,54325,435,43,423)

239044
55899


In [ ]:
myfunction("sum",10,20,30,40) --> 10+20+30+40
myfunction("count",1,2,3,4,5,6,7) --> 7
myfunction("ffffff",1,2,3,4,5,6,7)  --> 지정되지않았습니다. - 경고문

In [153]:
def myfunction(func,*args):
    if func == "sum":
        result = 0
        for i in args:
            result = result + i
        return result
    elif func == "count":
        return len(args)
    else:
        return "check for your function parameter!!!"

In [154]:
a = myfunction("sum",10,20,30,40)
print a 
a = myfunction("count",1,2,3,4,5,6,7)
print a 
a = myfunction("ffffff",1,2,3,4,5,6,7)
print a

100
7
check for your function parameter!!!


In [155]:
def multifunc(a,b):
    return a+b, a-b, a*b, a/b , a+b+3

In [156]:
multifunc(10,30) --> 리턴값이 듀블 쓰는건 리스트랑 같음ㅇㅇ

(40, -20, 300, 0, 43)

In [ ]:
def sum2(a,b):
    result = a + b
    return result
sum2(10,20)

In [157]:
(lambda x,y:x+y)(10,30)

40

In [165]:
def myfunc(func,*args):
    if func == "sel1":
        sumresult = 0
        dexresult = 1
        for i in args:
            sumresult = sumresult + i
            dexresult = dexresult * i
        return sumresult,dexresult
    elif func == "sel2":
        return args[0],args[len(args)-1]
    else:
        return "이상해요~~에러메세지"

            

In [166]:
print myfunc("sel1",1,2,3,4,5)
print myfunc("sel2",1,2,3,4,5)
print myfunc("aaaa",1,2,3,4,5)

(15, 120)
(1, 5)
이상해요~~에러메세지


In [168]:
import numpy as np

In [172]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

data3 = [[1,2,3,4],[5,6,7,8]]
arr3 = np.array(data3)

In [174]:
print arr1
print arr1.ndim
print arr1.shape
print arr1.dtype

print arr3
print arr3.ndim
print arr3.shape
print arr3.dtype

[ 6.   7.5  8.   0.   1. ]
1
(5L,)
float64
[[1 2 3 4]
 [5 6 7 8]]
2
(2L, 4L)
int32


In [178]:
#자료형 바꾸는방법
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int8)
arr3 = np.array([1,2,3],dtype = np.string_)

print arr1
print arr2
print arr3

#변경수행 함수 astype
arr3 = arr3.astype(np.float64)
print arr3


[ 1.  2.  3.]
[1 2 3]
['1' '2' '3']
[ 1.  2.  3.]


In [ ]:
#배열 스칼라간 연산.

#NumPy 색인/슬라이싱 
##리스트와 비슷하게 정수 인덱스 사용 한다.

In [181]:
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print list1
print arr1

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [183]:
print list1[0:3]
print arr1[0:3]

[1, 2, 3]
[1 2 3]


In [184]:
print list1[1:3]
print arr1[1:3]

[2, 3]
[2 3]


In [185]:
print list1[:3]
print arr1[:3]

[1, 2, 3]
[1 2 3]


In [186]:
print list1[3:]
print arr1[3:]

[4, 5, 6]
[4 5 6]


In [187]:
print list1[:]
print arr1[:]

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [191]:
arr1 = np.arange(10)
print arr1

[0 1 2 3 4 5 6 7 8 9]


In [192]:
arr1[2:9:3]#2부터9까지인데 3간격으로 가져오라는뜻

array([2, 5, 8])

In [193]:
arr1[::2]

array([0, 2, 4, 6, 8])

In [197]:
#2차원배열의 하나의 샘플을 만들어보자.

np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [198]:
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

In [199]:
np.arange(0,51,10)[:,np.newaxis] #모든원소들을 가로로 되있는걸 세로로 바꿔주게 되는기능이다.

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [203]:
a = np.arange(6) + np.arange(0,51,10)[:,np.newaxis]
print a

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [204]:
print a[2]
print "-------"
print a[0,2]#세로,가로
print "-------"

print a[0:2,3]#세로,가로

[20 21 22 23 24 25]
-------
2
-------
[ 3 13]


In [205]:
a[4:,4:]#이런식의 응용도 가능하다.

array([[44, 45],
       [54, 55]])

In [226]:
a[0,3:5]

array([3, 4])

In [228]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [229]:
a[2::2,::2] #이런식으로 간격을 줄수도있다.

array([[20, 22, 24],
       [40, 42, 44]])

In [230]:
#Boolean Indexing 
print arr1
print arr1<5
print arr1[arr1<5]

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [237]:
names = np.array(['Bob',"Joe","Will","Bob","Will","Joe","Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [236]:
data = np.random.randint(low = 30,high = 100, size=(7,4))
data

array([[60, 93, 74, 90],
       [77, 67, 79, 96],
       [66, 77, 62, 64],
       [62, 98, 55, 54],
       [34, 78, 80, 45],
       [92, 90, 53, 93],
       [63, 31, 76, 71]])

In [238]:
data[names=="Bob"]

array([[60, 93, 74, 90],
       [62, 98, 55, 54]])

In [240]:
data[[0,3],]

array([[60, 93, 74, 90],
       [62, 98, 55, 54]])

In [242]:
#밥이 두명이있는데 이중에 뒤에 두 성적만 보고싶을경우
data[names=="Bob",2:]

array([[74, 90],
       [55, 54]])

In [243]:
#첫번째 밥만 보고싶을경우
data[names=="Bob"][0]

array([60, 93, 74, 90])

In [244]:
#이름이 밥/윌인 사람들의 성정을 보고싶을경우 
data[(names == "Bob")|(names == "Will")]

array([[60, 93, 74, 90],
       [66, 77, 62, 64],
       [62, 98, 55, 54],
       [34, 78, 80, 45]])

In [249]:
data = np.random.randint(low = 30,high = 100, size=(7,4))
data
print data
data[data<=70] = 0
print data
data[data>70] = 1
print data
np.where(data>0)#두개의 인덱스를 반환해주는데 조건에 맞는 가로순서와 조건에 맞는 세로순서를 반환함.


#이를바탕으로 이름에대한 유니크한 index를 찾아서 누가 패스했는지 알아보자
print np.unique((np.where(data>0)[0]))#유니크하다는건 중복되는걸 지우는 함수
print names[np.unique(np.where(data>0)[0])]

[[59 59 74 44]
 [84 61 94 65]
 [37 83 64 49]
 [76 74 52 64]
 [81 46 52 41]
 [63 90 69 81]
 [49 94 35 72]]
[[ 0  0 74  0]
 [84  0 94  0]
 [ 0 83  0  0]
 [76 74  0  0]
 [81  0  0  0]
 [ 0 90  0 81]
 [ 0 94  0 72]]
[[0 0 1 0]
 [1 0 1 0]
 [0 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [0 1 0 1]
 [0 1 0 1]]
[0 1 2 3 4 5 6]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [251]:
arr = np.arange(32)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [252]:
arr = arr.reshape(4,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [256]:
arr = arr.reshape(2,16)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [257]:
arr1 = np.arange(10)
print arr1

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#속도차이를 보여준다.
#->결론: 기존에 쓰던 함수에 구현된기능이있으면 무조건 그걸 쓰자. 그래야 퍼포먼스가 나온다.